name: ci

on: [push, pull_request]

env:
  YARN_CACHE_DIR: .cache/yarn

jobs:
  deploy-pages:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        uses: actions/cache@v2
        with:
          path: ${YARN_CACHE_DIR}
          key: ${{ runner.os }}-yarn-cache-v1
      - run: yarn --frozen-lockfile --non-interactive

      - name: Build docs
        run: yarn run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
